**Numpy, Arrays**

In [6]:
import numpy as np

In [8]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)

[0 1 2 3 4 5 6 7 8 9]


*Here is a function that tells the lenth a.k. number of elements in the array*

In [11]:
np1.shape

(10,)

*Arrange func*

In [14]:
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


*Step*

In [17]:
np2 = np.arange(0, 10, 2)
print(np2)

[0 2 4 6 8]


*Zeros*

In [20]:
np3 = np.zeros(10)
print(np3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


*Multidimensional Zeros*

In [23]:
np4 = np.zeros((2, 10))
print(np4)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


*Full*

In [26]:
np5 = np.full((10), 6)
print(np5)

[6 6 6 6 6 6 6 6 6 6]


*Multidimensional Full*

In [29]:
np7 = np.full((2,10), 9)
print(np7)

[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]]


*Convert Python list to np*

In [32]:
myList = [1,2,3,4,5] 
np8 = np.array(myList)
print(np8)

[1 2 3 4 5]


**Slicing np Arrays**

In [35]:
np1 = np.array([1,2,3,4,5,6,7,8,9 ])

*Return 2,3,4,5*

In [38]:
print(np1[1:5])

[2 3 4 5]


*Return from something till the end of the array*

In [41]:
print(np1[3:])

[4 5 6 7 8 9]


*Return Negative Slices*

In [44]:
print(np1[-3 : -1])

[7 8]


*Step*

In [47]:
print(np1[1:5:2])

[2 4]


*Steps on the entire array*

In [50]:
print(np1[::2])

[1 3 5 7 9]


*Slice a 2-d array*

In [53]:
np2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

*Pull out a sinlge item*

In [56]:
print(np2[1,2])

8


*Slice a 2-d array*

In [59]:
print(np2[0 : 1, 1 : 3]) #0 : 1 means from 2d array first row first 1d array

[[2 3]]


In [61]:
print(np2[0 : 2, 1 : 3])

[[2 3]
 [7 8]]


**Numpy Universal Functions**

In [64]:
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])
print(np1)

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]


*Square root of each elements* 

In [67]:
#print(np.sqrt(np1))

*Absolute Values*

In [70]:
#print(np.absolute(np1))

*Exponentials*

In [73]:
#print(np.exp(np1))

*Min/Max*

In [76]:
print(np.max(np1))
print(np.min(np1))

9
-3


*Sign (+, -)*

In [79]:
print(np.sign(np1))

[-1 -1 -1  0  1  1  1  1  1  1  1  1  1]


*Trig Sin Cos log*

In [82]:
print(np.sin(np1))

[-0.14112001 -0.90929743 -0.84147098  0.          0.84147098  0.90929743
  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825
  0.41211849]


In [84]:
#print(np.log(np1))

**Copy vs View**

In [87]:
np1 = np.array([0,1,2,3,4,5])

*Create a view*

In [90]:
#np2 = np1.view()

In [92]:
#print(f'Original np1 {np1}')
#print(f'Original np2 {np2}')

In [94]:
#np1[0] = 42
#print(f'Original np1 {np1}')
#print(f'Original np2 {np2}')

*Create a Copy*

In [97]:
np2 = np1.copy()

In [99]:
print(f'Original np1 {np1}')
print(f'Original np2 {np2}')

Original np1 [0 1 2 3 4 5]
Original np2 [0 1 2 3 4 5]


In [101]:
np2[0] = 49
print(f'Original np1 {np1}')
print(f'Original np2 {np2}')

Original np1 [0 1 2 3 4 5]
Original np2 [49  1  2  3  4  5]


**Shape and Reshape**

*#Create 1D array and Get Shape*

In [105]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1)
print(np1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


*#Create 2D array and Get Shape*

In [108]:
np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np2)
print(np2.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


*#Reshaping into 2D*

In [111]:
np3 = np1.reshape(3,4)
print(np3)
print(np3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


*#Reshaping into 3D*

In [114]:
np4 = np1.reshape(2,3,2)
print(np4)
print(np4.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


*#Flatten to 1D*

In [117]:
np5 = np4.reshape(-1)
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


**Iterations**

In [120]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
for x in np1:
    print(x)

1
2
3
4
5
6
7
8
9
10


*#2D array*

In [123]:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np2:
    print(x) #prints Rows

[1 2 3 4 5]
[ 6  7  8  9 10]


In [125]:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np2:
    print(x) #prints Rows
    for y in x:
        print(y)

[1 2 3 4 5]
1
2
3
4
5
[ 6  7  8  9 10]
6
7
8
9
10


*#3D array*

In [128]:
np3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
for x in np3:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [130]:
np3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
for x in np3:
    #print(x)
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [132]:
np3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
for x in np3:
    #print(x)
    for y in x:
        #print(y)
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


*#Use np.nditer()*

In [135]:
for x in np.nditer(np3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


**Sorting numpy arrays**

*#np.sort* *numerical*

In [156]:
np1 = np.array([6,7,4,9,0,2,1])
print(np.sort(np1))

[0 1 2 4 6 7 9]


*#np.sort* *alphabetical*

In [159]:
np2 = np.array(["John", "Vera", "Tina", "Aeron", "Zed"])
print(np.sort(np2))

['Aeron' 'John' 'Tina' 'Vera' 'Zed']


In [161]:
np3 = np.array([True, False, False, True])
print(np3)
print(np.sort(np3))

[ True False False  True]
[False False  True  True]


*#Return copy not an original array*

In [170]:
print(np1)
print(np.sort(np1))
print(np1)

[6 7 4 9 0 2 1]
[0 1 2 4 6 7 9]
[6 7 4 9 0 2 1]


*#2D array*

In [173]:
np4 = np.array([[6,7,1,9], [8,3,5,0]])
print(np4)
print(np.sort(np4))

[[6 7 1 9]
 [8 3 5 0]]
[[1 6 7 9]
 [0 3 5 8]]


**Search**

In [182]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10,3])
x = np.where(np1 == 3)
print(x[0])
print(np1[x[0]])

[ 2 10]
[3 3]


*#Even items*

In [190]:
y = np.where(np1 % 2 == 0)
print(y[0])

[1 3 5 7 9]


*#Odd items* 

In [193]:
z = np.where(np1 % 2 == 1)
print(z[0])

[ 0  2  4  6  8 10]
